language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t plato28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plato28/react-test npm test

after_success:
  - docker build -t plato28/multi-client ./client
  - docker build -t plato28/multi-nginx ./nginx
  - docker build -t plato28/multi-server ./server
  - docker build -t plato28/multi-worker ./worker
  # LOG IN TO THE DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAKE THOSE IMAGES AND PUSH THEM TO DOCKER HUB
  - docker push plato28/multi-client
  - docker push plato28/multi-nginx
  - docker push plato28/multi-server
  - docker push plato28/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-plato
  env: MultiPlato-env
  bucket_name: elasticbeanstalk-ap-northeast-2-822637900730
  bucket_path: multi-plato
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  